name: Build & Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package --file backend/pom.xml # backend path ka dhyan rakhna
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: backend/target/*.jar
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: my-tf-nodeapp # Terraform wale app service ka name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/target/*.jar
