name: Build & Deploy Spring Boot to Azure

on:
  push:
    branches:
      - maino

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn clean package --file backend/pom.xml
      - run: zip app.zip backend/target/*.jar
      - uses: azure/webapps-deploy@v3
        with:
          app-name: my-tf-nodeapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
